# Generated by Django 5.1.4 on 2026-09-26 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_email', models.EmailField(blank=True, max_length=254)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('_refresh_token', models.TextField(blank=True, db_column='refresh_token_enc')),
                ('brief_time', models.CharField(default='07:30', help_text='Local HH:MM', max_length=5)),
                ('briefings_enabled', models.BooleanField(default=True)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_date', models.CharField(db_index=True, max_length=10)),
                ('headline', models.CharField(max_length=500)),
                ('body_markdown', models.TextField()),
                ('items_json', models.JSONField(default=list)),
                ('event_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('delivered', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='assistant.account')),
            ],
            options={
                'db_table': 'briefs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'for_date'), name='uq_account_date')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=1024)),
                ('event_summary', models.CharField(max_length=1024)),
                ('event_starts_at', models.DateTimeField()),
                ('fire_at', models.DateTimeField(db_index=True)),
                ('offset_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='assistant.account')),
            ],
            options={
                'db_table': 'reminders',
                'ordering': ['fire_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'event_id', 'offset_minutes'), name='uq_reminder_offset')],
            },
        ),
        migrations.CreateModel(
            name='SeenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=1024)),
                ('summary', models.CharField(blank=True, max_length=1024)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_events', to='assistant.account')),
            ],
            options={
                'db_table': 'seen_events',
                'indexes': [models.Index(fields=['account', 'event_id'], name='seen_events_account_308c51_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'event_id'), name='uq_account_event')],
            },
        ),
    ]
