# Generated by Django 5.2.17 on 2026-09-28 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('all_day', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('google', 'Google')], default='manual', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assistant.account')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['start'],
                'indexes': [models.Index(fields=['account', 'start'], name='events_account_e2c8c0_idx')],
            },
        ),
    ]
